FROM node:18 as builder
WORKDIR /app
COPY package.json package-lock.json /app/
RUN npm ci
COPY ./ /app/
ARG MQTT_BROKER_URL
ARG VOICE_SERVER_ENDPOINT
ARG VOICE_SERVER_BEARER_TOKEN
ARG BUILDTIME=unknown
ARG VERSION=unknown
ARG REVISION=unknown
ENV VITE_MQTT_BROKER_URL $MQTT_BROKER_URL
ENV VITE_VOICE_SERVER_SERVER_ENDPOINT $VOICE_SERVER_ENDPOINT
ENV VITE_VOICE_SERVER_BEARER_TOKEN $VOICE_SERVER_BEARER_TOKEN
ENV VITE_BUILDTIME $BUILDTIME
ENV VITE_VERSION $VERSION
ENV VITE_REVISION $REVISION
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80