name: Checking

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

jobs:
  check-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-check-web-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-check-web-

      - run: npm ci
      - run: npm run check
